import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3"

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
})
const prisma = new PrismaClient({ adapter })

const categories = [
  { name: "Rings", slug: "rings", sortOrder: 1 },
  { name: "Earrings", slug: "earrings", sortOrder: 2 },
  { name: "Bangles & Bracelets", slug: "bangles-bracelets", sortOrder: 3 },
  { name: "Pendants & Lockets", slug: "pendants", sortOrder: 4 },
  { name: "Jewelry Sets", slug: "jewelry-sets", sortOrder: 5 },
  { name: "Mala & Mala Sets", slug: "mala", sortOrder: 6 },
  { name: "Stainless Steel", slug: "stainless-steel", sortOrder: 7 },
  { name: "Hair Accessories", slug: "hair-accessories", sortOrder: 8 },
  { name: "Other Jewelry", slug: "other", sortOrder: 9 },
]

const products = [
  {
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    sku: "CETH141",
    price: 199,
    compareAtPrice: 400,
    image: "/products/earrings.svg",
    collection: "drops",
    featured: true,
    onSale: true,
    isNew: false,
    reviewCount: 150,
    rating: 4.8,
    categorySlug: "earrings",
    description:
      "Elegant pearl drop earrings for everyday sparkle. Lightweight, comfortable, and perfect for casual or party wear.",
  },
  {
    name: "Butterfly Stud Earrings",
    slug: "butterfly-stud-earrings",
    sku: "CETH550",
    price: 199,
    compareAtPrice: 400,
    image: "/products/earrings.svg",
    collection: "studs",
    featured: true,
    onSale: true,
    isNew: true,
    reviewCount: 102,
    rating: 4.7,
    categorySlug: "earrings",
    description:
      "Viral butterfly studs with a soft shine. A TinyGems favourite for daily wear.",
  },
  {
    name: "Floral Zircon Tops",
    slug: "floral-zircon-tops",
    sku: "CETH259",
    price: 199,
    compareAtPrice: 400,
    image: "/products/earrings.svg",
    collection: "floral",
    featured: true,
    onSale: true,
    isNew: false,
    reviewCount: 111,
    rating: 4.9,
    categorySlug: "earrings",
    description:
      "Floral zircon tops that catch the light. Pair with both eastern and western outfits.",
  },
  {
    name: "Tai Earrings",
    slug: "tai-earrings",
    sku: "CETH165",
    price: 179,
    compareAtPrice: 499,
    image: "/products/earrings.svg",
    collection: "jhumki",
    featured: false,
    onSale: true,
    isNew: false,
    reviewCount: 39,
    rating: 4.6,
    categorySlug: "earrings",
    description: "Statement tai earrings with a festive silhouette at a sale price.",
  },
  {
    name: "Gold-Tone Casual Ring",
    slug: "gold-tone-casual-ring",
    sku: "CRGH085",
    price: 449,
    compareAtPrice: 939,
    image: "/products/rings.svg",
    collection: "casual",
    featured: true,
    onSale: true,
    isNew: false,
    reviewCount: 16,
    rating: 4.5,
    categorySlug: "rings",
    description: "Adjustable gold-tone casual ring with a polished everyday finish.",
  },
  {
    name: "Zircon Halo Ring",
    slug: "zircon-halo-ring",
    sku: "TRGH001",
    price: 399,
    compareAtPrice: 739,
    image: "/products/rings.svg",
    collection: "zircon",
    featured: true,
    onSale: true,
    isNew: true,
    reviewCount: 26,
    rating: 4.7,
    categorySlug: "rings",
    description: "Sparkling zircon halo ring designed for parties and gifts.",
  },
  {
    name: "Farshi Kundan Ring",
    slug: "farshi-kundan-ring",
    sku: "KR001",
    price: 699,
    compareAtPrice: 1398,
    image: "/products/rings.svg",
    collection: "kundan",
    featured: false,
    onSale: true,
    isNew: false,
    reviewCount: 12,
    rating: 4.8,
    categorySlug: "rings",
    description: "Traditional farshi kundan ring with an ethnic festive look.",
  },
  {
    name: "Tulip Bracelet",
    slug: "tulip-bracelet",
    sku: "TBR101",
    price: 299,
    compareAtPrice: 598,
    image: "/products/bracelets.svg",
    collection: "floral",
    featured: true,
    onSale: true,
    isNew: true,
    reviewCount: 88,
    rating: 4.9,
    categorySlug: "bangles-bracelets",
    description:
      "The viral tulip bracelet — a delicate floral piece at a TinyGems price.",
  },
  {
    name: "Chain Bracelet Gold",
    slug: "chain-bracelet-gold",
    sku: "TBC210",
    price: 349,
    compareAtPrice: 699,
    image: "/products/bracelets.svg",
    collection: "casual",
    featured: false,
    onSale: true,
    isNew: false,
    reviewCount: 44,
    rating: 4.6,
    categorySlug: "bangles-bracelets",
    description: "Imported trendy chain bracelet in a warm gold tone.",
  },
  {
    name: "Ethnic Kundan Bangles",
    slug: "ethnic-kundan-bangles",
    sku: "KB330",
    price: 899,
    compareAtPrice: 1590,
    image: "/products/bangles.svg",
    collection: "kundan",
    featured: true,
    onSale: true,
    isNew: false,
    reviewCount: 31,
    rating: 4.8,
    categorySlug: "bangles-bracelets",
    description: "Pair of farshi kundan bangles for weddings and mehndi.",
  },
  {
    name: "Calligraphy Pendant Set",
    slug: "calligraphy-pendant-set",
    sku: "CPS001",
    price: 399,
    compareAtPrice: 798,
    image: "/products/pendants.svg",
    collection: "calligraphy",
    featured: true,
    onSale: true,
    isNew: true,
    reviewCount: 22,
    rating: 4.9,
    categorySlug: "pendants",
    description: "Elegant calligraphy pendant with matching earrings.",
  },
  {
    name: "Kundan Pendant Set",
    slug: "kundan-pendant-set",
    sku: "KPS010",
    price: 790,
    compareAtPrice: 1490,
    image: "/products/pendants.svg",
    collection: "kundan",
    featured: false,
    onSale: true,
    isNew: false,
    reviewCount: 18,
    rating: 4.7,
    categorySlug: "pendants",
    description: "Farshi kundan pendant set with a rich festive finish.",
  },
  {
    name: "Ethnic Necklace Set",
    slug: "ethnic-necklace-set",
    sku: "PNS220",
    price: 1290,
    compareAtPrice: 2490,
    image: "/products/sets.svg",
    collection: "ethnic",
    featured: true,
    onSale: true,
    isNew: false,
    reviewCount: 27,
    rating: 4.8,
    categorySlug: "jewelry-sets",
    description: "Complete ethnic necklace set for parties and shaadi functions.",
  },
  {
    name: "Polki Choker Set",
    slug: "polki-choker-set",
    sku: "PCK110",
    price: 1590,
    compareAtPrice: 2990,
    image: "/products/sets.svg",
    collection: "choker",
    featured: true,
    onSale: true,
    isNew: true,
    reviewCount: 14,
    rating: 4.9,
    categorySlug: "jewelry-sets",
    description: "Bridal-ready polki choker with earrings. Statement TinyGems set.",
  },
  {
    name: "Pearl Bead Mala",
    slug: "pearl-bead-mala",
    sku: "PML040",
    price: 990,
    compareAtPrice: 1890,
    image: "/products/mala.svg",
    collection: "floral",
    featured: false,
    onSale: true,
    isNew: false,
    reviewCount: 19,
    rating: 4.6,
    categorySlug: "mala",
    description: "Layered pearl and bead mala for festive layering.",
  },
  {
    name: "Kundan Mala Set",
    slug: "kundan-mala-set",
    sku: "KML055",
    price: 1490,
    compareAtPrice: 2790,
    image: "/products/mala.svg",
    collection: "kundan",
    featured: true,
    onSale: true,
    isNew: true,
    reviewCount: 11,
    rating: 4.8,
    categorySlug: "mala",
    description: "Heavy kundan mala set with a traditional bridal feel.",
  },
  {
    name: "Stainless Steel Necklace",
    slug: "stainless-steel-necklace",
    sku: "SSN001",
    price: 349,
    compareAtPrice: 698,
    image: "/products/stainless.svg",
    collection: "casual",
    featured: true,
    onSale: true,
    isNew: true,
    reviewCount: 9,
    rating: 4.7,
    categorySlug: "stainless-steel",
    description: "Anti-tarnish stainless steel necklace for daily wear.",
  },
  {
    name: "Stainless Steel Bracelet",
    slug: "stainless-steel-bracelet",
    sku: "SSB002",
    price: 299,
    compareAtPrice: 598,
    image: "/products/stainless.svg",
    collection: "casual",
    featured: false,
    onSale: true,
    isNew: true,
    reviewCount: 7,
    rating: 4.6,
    categorySlug: "stainless-steel",
    description: "Minimal stainless steel bracelet that will not fade.",
  },
  {
    name: "Hair Pin Set",
    slug: "hair-pin-set",
    sku: "HPN011",
    price: 149,
    compareAtPrice: 299,
    image: "/products/hair.svg",
    collection: "floral",
    featured: false,
    onSale: true,
    isNew: false,
    reviewCount: 21,
    rating: 4.5,
    categorySlug: "hair-accessories",
    description: "Decorative hair pins for party bun and braid styles.",
  },
  {
    name: "Matha Patti",
    slug: "matha-patti",
    sku: "MTH001",
    price: 890,
    compareAtPrice: 1690,
    image: "/products/other.svg",
    collection: "bridal",
    featured: false,
    onSale: true,
    isNew: false,
    reviewCount: 8,
    rating: 4.7,
    categorySlug: "other",
    description: "Traditional matha patti for bridal and mehndi looks.",
  },
]

async function main() {
  await prisma.product.deleteMany()
  await prisma.category.deleteMany()

  for (const category of categories) {
    await prisma.category.create({ data: category })
  }

  const dbCategories = await prisma.category.findMany()
  const bySlug = Object.fromEntries(dbCategories.map((c) => [c.slug, c.id]))

  for (const product of products) {
    const { categorySlug, ...data } = product
    await prisma.product.create({
      data: {
        ...data,
        category: { connect: { id: bySlug[categorySlug] } },
        studioImage: "/products/stainless.svg",
        wornImage:
          categorySlug === "other" || categorySlug === "hair-accessories"
            ? "/products/hair.svg"
            : "/products/sets.svg",
      },
    })
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (error) => {
    console.error(error)
    await prisma.$disconnect()
    process.exit(1)
  })
